// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2yEdOVpzgvu_bcY8FuhyQK4PzFoxXQAA',
    appId: '1:1041571634549:web:1b933f58e2dbb92f59073c',
    messagingSenderId: '1041571634549',
    projectId: 'artify-3b638',
    authDomain: 'artify-3b638.firebaseapp.com',
    storageBucket: 'artify-3b638.appspot.com',
    measurementId: 'G-BVF6E83QRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxW7p_yeT-2C0Itw37HEgA3DTBzZ8z-HY',
    appId: '1:1041571634549:android:5868129e2a4184dc59073c',
    messagingSenderId: '1041571634549',
    projectId: 'artify-3b638',
    storageBucket: 'artify-3b638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvTaJUQ-yVg8Adwo589BAejDDGFzH_yq0',
    appId: '1:1041571634549:ios:2376f88055db69ca59073c',
    messagingSenderId: '1041571634549',
    projectId: 'artify-3b638',
    storageBucket: 'artify-3b638.appspot.com',
    iosClientId: '1041571634549-pqej86vcn44crui08b8m3mp1415hg21a.apps.googleusercontent.com',
    iosBundleId: 'com.example.artify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvTaJUQ-yVg8Adwo589BAejDDGFzH_yq0',
    appId: '1:1041571634549:ios:2376f88055db69ca59073c',
    messagingSenderId: '1041571634549',
    projectId: 'artify-3b638',
    storageBucket: 'artify-3b638.appspot.com',
    iosClientId: '1041571634549-pqej86vcn44crui08b8m3mp1415hg21a.apps.googleusercontent.com',
    iosBundleId: 'com.example.artify',
  );
}
